# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics

on:
  # Schedule updates (each day)
  schedule:
    - cron: "* 0 * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Cache GitHub Actions runner dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 2: Install dependencies (if not already cached)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Run the Metrics action
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          user: larsrollik
          template: classic
          filename: metrics-base.svg
          base: header, activity, community, repositories
          config_timezone: Europe/London
